# Generated by Django 2.2.9 on 2020-10-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyprice',
            old_name='Date',
            new_name='date',
        ),
    ]
