# Generated by Django 2.2.9 on 2020-10-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20201015_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='symbol',
            field=models.CharField(max_length=7),
        ),
        migrations.DeleteModel(
            name='Symbols',
        ),
    ]
